# Generated by Django 2.1.3 on 2018-12-05 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_tp2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='usuario',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
